version: '3.8'

services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: your_db_name
      POSTGRES_USER: your_db_user
      POSTGRES_PASSWORD: your_db_password
    networks:
      - backend
      - frontend

  redis:
    image: redis:latest
    networks:
      - backend

  backend:
    build: ./backend
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      DEBUG: '1'
      DJANGO_DB_HOST: db
      DJANGO_DB_NAME: your_db_name
      DJANGO_DB_USER: your_db_user
      DJANGO_DB_PASSWORD: your_db_password
      REDIS_HOST: redis
    networks:
      - backend

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    networks:
      - frontend

networks:
  backend:
  frontend:

volumes:
  postgres_data:
